#This is the permission needed to execute the /wpredstone command. (The command only has a reload function).
WaterproofRedstonePermission: 'wpredstone.command'
#This message will be sent to the player executing the command if they don't have permission to use it.
NoPermission: '&cYou do not have permission to use this command.'
#This message will be sent to the player executing the command if they only provided 1 argument (e.g. they only typed /wpredstone).
InvalidSyntax: '&cInvalid command usage: /wpredstone <reload>'
#This message will be sent to the player if the config has been reloaded.
ConfigReloaded: '&cConfig reloaded.'

#This will enable 1 hit kills if true.
EnableWaterproofRedstone: true